# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datetest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=100, verbose_name='公众号')),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='词名')),
                ('freq', models.DecimalField(decimal_places=10, max_digits=12, verbose_name='词频')),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('publish_time', models.DateField(verbose_name='发表时间')),
                ('dianzan', models.IntegerField(verbose_name='点赞数')),
                ('yuedu', models.IntegerField(verbose_name='阅读数')),
                ('text', models.TextField(verbose_name='文章内容')),
                ('aboutwords', models.ManyToManyField(to='show.Keyword')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.Dept')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
    ]
