# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='releate',
            field=models.IntegerField(default=0, verbose_name='相关文章数'),
        ),
    ]
