# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0003_passage_passagehot'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='departmentname',
            field=models.CharField(default='null', max_length=100, verbose_name='部门名'),
        ),
    ]
