# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0004_passage_departmentname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word1', models.CharField(max_length=100)),
                ('word2', models.CharField(max_length=100)),
                ('relation', models.IntegerField(default=0)),
            ],
        ),
    ]
