# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0005_relate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datetest',
        ),
    ]
